ecommerceproject/accounts/urls.py
from django.urls import path
from . import views
urlpatterns=[
  path('register/',views.register,name="register"),
  path('login/',views.login,name="login"),
  path('logout/',views.logout,name="logout"),

]

ecommerceproject/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),


]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include


from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('foodcourt/',include('foodcourt.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerceproject/foodcourt/urls.py
from django.urls import path
from  . import views
app_name='foodcourt'
urlpatterns = [

    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatdetail'),

]

ecommerceproject/search_app/urls.py
from django.urls import path
from . import views

app_name="search_app"

urlpatterns=[

    path('',views.SearchResult,name='SearchResult'),

]

ecommerceproject/cart/models.py
from django.db import models
from  foodcourt.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price*self.quantity
    def __str__(self):
        return '{}'.format(self.product)

ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from  foodcourt.models import Product
from  .models import  Cart,CartItem
from  django.core.exceptions import ObjectDoesNotExist

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
                cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity= 1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items= None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return  render(request,'cart.html',dict(cart_items = cart_items,total = total,counter = counter))


def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return  redirect('cart:cart_detail')
def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return  redirect('cart:cart_detail')

ecommerceproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <meta name="description" content="{% block metadescription %}{% endblock%}">

    <title>{% block title %}{% endblock %} </title>
</head>
<body>
<div  class="container">


{% include 'header.html' %}
{% include 'navbar.html' %}
{%  block content %}
{% endblock %}
    </div>
{% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
This is the cart page. proceed to review your items and place the order
{% endblock %}
{% block title %}
    Cart -FOOD COURT PVT LTD
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>

        <h1 class="text-center my_title">
            Your Shopping Cart is empty
        </h1>
        <br>
        <p class="text-center">
            Please Click <a href="{% url 'foodcourt:allProdCart' %}">Here</a>to continue shopping.


        </p>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
        <br>
    </div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    Your Items:
                </th>

            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" style="width:100px;height:100px;" class="float-left rounded custom_image"></a>

                </td>
                <td class="text-lef">
                    {{cart_item.product.name}}
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    Price: $ {{cart_item.product.price }}
                    <br>
                    Qty : {{cart_item.quantity}} x $ {{cart_item}}
                </td>
                <td>
                    $ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url  'cart:add_cart' cart_item.product.id %} " class="custom_a"> <i class="fa fa-plus custom_icon"> </i></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                </td>
                {% else %}
                 <td>

                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
            <th>
                Checkout
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>

            <td>
                Please review your shopping cart items before proceeding with the order payment.
            </td>
        </tr>
        <tr>
            <td class="text-left">
                Your Total is : <strong> {{ total }}</strong>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="mx-auto">
        <a href="{% url 'foodcourt:allProdCat' %} " class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>

</div>
    {% endif %}
</div>
</div>
</div>

{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description |truncatewords:155 }}
    {% else %}
        Welcome to the food court where you can buy  awesome items .
    {% endif %}
{% endblock %}
{% block title %}
     {% if category %}
        {{category.name}}-Shop cart
    {% else %}
        FOOD COURT PRODUCTS -shop cart
    {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
        <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'foodcourt:allProdCat' %}">FOOD COURT BAKE FOODS ARE HERE</a>{{ category.name }}</p>
            </div>
        </div>
    {% endif %}
<div class="mx-auto">
    {% if category %}
        <img  class="my_image" src="{{category.image.url}}" style="height:350px;" alt="{{category.name}}">

</div><br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.desc}}</p>
</div>
{% else %}
<div>
    <center><img  class="my_image my_image_padding" src="{% static 'img/foodtemp3.png'  %}"  style="width:1100px;height:700px" alt=""></center>
</div>
<br>
<div>
    <h1 class="text-center my_title"> FOODCOURT BAKE FOODS ARE HERE</h1>
    <p class="text-justify">FOODCOURT bakery is an establishment that produces and sells flour-based food baked in an oven such as bread, cookies, cakes, pastries, and pies. Some retail bakeries are also categorized as cafés, serving coffee and tea to customers who wish to consume the baked goods on the premises.</p>
</div>
{% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12  col-md-4 xol-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" style="width:200px;height:250px;" alt="{{product.name}}"></a>
            <div class="card-body">
               <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
            </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}"  class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>

{% endblock %}

ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom  my_footer">
    <p class="text-center">&copy; FOOD COURT pvt ltd.All rights Reserved</p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'foodcourt:allProdCat' %}"> <img src="{% static 'img/foodtemp2.png' %}" style="width:120px;height:130px" alt="logimage"></a>
    </center>
</header>

ecommerceproject/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        welcome to Flipkart!!.
{% endblock %}
{% block title %}
     Login Here !
{% endblock %}
{% block content %}

<form action="login" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username"><br>
    <input type="password" name="password" placeholder="password"><br>
    <input type="submit" value="Login">
</form>
{% endblock %}

ecommerceproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

         {% if user.is_authenticated %}

          <li>Hai {{user.username}}</li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
          {% else %}
          <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:register' %}">signup</a></li>

          <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
          {% endif %}

        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'foodcourt:allProdCat' %}">All Products</a></li>
               {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
                {% endfor %}

          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get" >
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search"  name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search" ></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{ product.description|truncatewords:155 }}



{% endblock %}
{% block title %}
    {% if category %}
        {{ product.name }} - ABC Store

    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p> <a href="{% url 'foodcourt:allProdCat' %}">Home</a> | <a href ="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" style="width:200px;height:300px" alt="{{product.name}}">

        </div>
    </div>

     <div class="col-12 col-sm-12 col-md-12 col-lg-6">
         <div>
         <h1 class="my_prod_title">{{product.name}}</h1>
         <p>${{product.price}}</p>
         <p class="my_title"> Product Description</p>
         <p class="text-justify my_rod_text">{{product.description}}</p>
         {% if  product.stock <= 0 %}
         <p class="text-justify my_prod_text"><b>Out of stock</b></p>
         {% else %}
         <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
         {% endif%}

     </div>
 </div>
</div>
</div>
</div>
{% endblock  %}

ecommerceproject/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        welcome to the cart store where can you buy awesome items!!.
{% endblock %}
{% block title %}
     Sign up Here !
{% endblock %}
{% block content %}
<form action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username"><br>
    <input type="text" name="first_name" placeholder="firstname"><br>

    <input type="text" name="last_name" placeholder="last_name"><br>

    <input type="email" name="email" placeholder="email"><br>

    <input type="password" name="password1" placeholder="password"><br>

    <input type="password" name="password2" placeholder="confirm password"><br>

    <input type="submit" value="Sign Up">

</form>
<div>
    {% for message in messages %}
    <h4>{{message}}</h4>
    {% endfor %}
</div>

{% endblock %}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        We have variety of products .
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for :<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12  col-md-4 xol-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
            <div class="card-body">
               <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
            </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text"> 0 results found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}